### ISSUE TITLE
Invalid data provided exception when confirming user with UserStoreBasedIdentityDataStore

### ISSUE THREAD

**Issue by shammijayasinghe** [wso2/carbon-identity-framework#1568]
**Description:**
WSO2 identity server 5.5.0 is throwing the **Caused by: org.wso2.carbon.user.core.UserStoreException: Invalid data provided** exception when we try to confirm the user registration via **confirmUserSelfRegistration** soap operation of the **UserInformationRecoveryService** admin service.

The complete exception thrown is 
`TID: [-1234] [] [2018-05-15 17:52:53,914] ERROR {org.wso2.carbon.identity.mgt.services.UserInformationRecoveryService} -  Error while validating confirmation code for user : foo@bar.com
org.wso2.carbon.identity.base.IdentityException: Error while persisting identity user data in to user store for user: foo@bar.com
        at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:60)
        at org.wso2.carbon.identity.mgt.store.UserStoreBasedIdentityDataStore.setUserClaimsValuesInUserStore(UserStoreBasedIdentityDataStore.java:230)
        at org.wso2.carbon.identity.mgt.store.UserStoreBasedIdentityDataStore.store(UserStoreBasedIdentityDataStore.java:85)
        at org.wso2.carbon.identity.mgt.util.UserIdentityManagementUtil.unlockUserAccount(UserIdentityManagementUtil.java:276)
        at org.wso2.carbon.identity.mgt.services.UserInformationRecoveryService.confirmUserSelfRegistration(UserInformationRecoveryService.java:1298)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212)
        at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageReceiver.java:117)
        at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40)
        at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
        at org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:173)
        at org.apache.axis2.transport.http.AxisServlet.doPost(AxisServlet.java:147)
        at org.wso2.carbon.core.transports.CarbonServlet.doPost(CarbonServlet.java:232)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:91)
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:60)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
        at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while getting claim attribute for user : foo@bar.com
        at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doSetUserClaimValues(JDBCUserStoreManager.java:2164)
        at com.wso2.carbon.custom.user.store.manager.CustomPrimaryUserStoreManager.doSetUserClaimValues(CustomPrimaryUserStoreManager.java:125)
        at org.wso2.carbon.identity.mgt.store.UserStoreBasedIdentityDataStore.setUserClaimsValuesInUserStore(UserStoreBasedIdentityDataStore.java:218)
        ... 64 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Invalid data provided
        at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.batchUpdateStringValuesToDatabase(JDBCUserStoreManager.java:3168)
        at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.updateProperties(JDBCUserStoreManager.java:3114)
        at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doSetUserClaimValues(JDBCUserStoreManager.java:2151)
        ... 66 more`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
IS 5.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Configure IS for JDBC user store by changing
   master-datasource.xml
  user-mgt.xml
2. Configure IS for Self sign up as in [2]. I have disable captcha verification and email sending.

3. Change the Identity.Mgt.User.Data.Store to org.wso2.carbon.identity.mgt.store.UserStoreBasedIdentityDataStore instead of having the default org.wso2.carbon.identity.mgt.store.JDBCIdentityDataStore in identity-mgt.properties

4. create a user invoking registerUser operation. You will get the confirmation code. 

5. use the above code for the request 

```
<confirmUserSelfRegistration xmlns="http://services.mgt.identity.carbon.wso2.org">
<username>foo@bar.com</username>
<code>10102ad0-39d2-4ac6-996f-ea9af43d5a60</code>
</confirmUserSelfRegistration>
```

[2] https://docs.wso2.com/display/IS520/Self+Sign+Up+and+Account+Confirmation

**Related Issues:**

**Comment by DMHP** [comment]
https://github.com/wso2/carbon-identity-framework/commit/856822015441a2c16c3c96d90efc55d1282c3fb9
